<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <DebugType>portable</DebugType>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
    <PathMap>$(MSBuildThisFileDirectory)=/_/</PathMap>
    <LangVersion>latest</LangVersion>
    <Version>2.2.1</Version>
  </PropertyGroup>
</Project>
